sudo: false
os: linux
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  matrix:
    - CXX=g++-4.8 TEST_SUITE=unit
matrix:
  include:
    - os: linux
      node_js: "4"
      env: CXX=g++-4.8 TEST_SUITE=coverage
    - os: linux
      node_js: "4"
      env: CXX=g++-4.8 TEST_SUITE=standard
script: npm run $TEST_SUITE
